# Copied from webforj/webforj-documentation (MIT, (c) 2022 webforJ; see LICENSES/webforJ-MIT.txt).
extends: substitution
message: "Use '%s' instead of '%s'."
level: warning
ignorecase: true
action:
  name: replace
swap:
  '(?<![\#-/])webforj(?![-/])': webforJ
  '(?<![\#-/])startforj(?![-/])': startforJ
  '(?<![\#-/])craftforj(?![-/])': craftforJ